### ISSUE TITLE
[GUI] v5 master branch - addresses don't go away despite being used.

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#1026]
![image](https://github.com/wizardsardine/liana/assets/15522963/b115ec06-c4a3-42c6-b7c5-c51832e759d8)

https://mempool.space/signet/address/tb1qtjv7ruwy57249j5g4g4jcwhctvwcnatc332jcl50yvtnzlch8cjs2vcxje

**Comment by edouardparis** [comment]
My first idea to fix this issue was to monitor coins and checks if one of them deposits to the address, but as [@darosior responded](https://github.com/wizardsardine/liana/pull/1032#issuecomment-2017627894):

> I disagree with the approach here. It seems like a bad hack to be honest. An address which was shared doesn't mean it was necessarily used onchain.

We agree to reintroduce instead the previous behavior:
Reset the list when user leave and come back to the receive panel ( #1035 )
