### ISSUE TITLE
Auto close broadcast modal after some delay

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#1143]
![image](https://github.com/wizardsardine/liana/assets/124568858/29c0f7e1-bb9d-4000-bf9c-eb99e632d881)

**Comment by nondiremanuel** [comment]
What does the delay accomplish here? 
If it's related to the fact that it's not very intuitive to click outside the modal to close it, I would solve it by adding a close ("x") button instead of inserting a delay. In this way we would still assure that the closure is an action of the user. This is a comment common to many modals in the application, so maybe it should be addressed in a separate issue (if not already present).

**Comment by pythcoiner** [comment]
> What does the delay accomplish here? 

Avoid one more click

I feel in the broadcast flow there is too musch click, user already click 2 times (after sign) for broadcast

**Comment by nondiremanuel** [comment]
@pythcoiner I think this is still a relevant issue, did you close it by mistake or is there a reason I'm not seeing?
