### ISSUE TITLE
Wording for v1

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#446]
We should go through all the wording all around the GUI and update it if necessary. I'm thinking for instance about tooltips, rescan, recovery, spend creation process.

**Comment by kloaec** [comment]
Bitcoin Mainnet -> Bitcoin
### Home
- "coins" don't expire, timelocks lapse/expire. -> Your next timelock will expire in ...
- I would put this sentence in grey instead of white, as it is a basic information. (unless within critical range, red.)
- Deposit: I think it makes sense, but maybe only in the context of a deposit from the owner of the wallet. Need to confirm with native English speakers.
### Send
- amount (ex:0.001) -> amount (in BTC)
- fee rate (Feerate) -> just keep the fee rate outside of the box, remove the "feerate" within the box.
- actually for both Amount and Fee rate, we should have the unit displayed in the box even after i enter an amount. Maybe it's too annoying to do now, but in the future we should.
- 1 spending path available -> 1 spending path IS available
- 1 spent coin -> 1 coin spent
- save the transaction as draft -> save this transaction as a draft
- Self send -> send to self
### coins
space between the comma and the number of days: expires in 5 months, 22 days
### PSBT
- the spend transaction was included in the blockchain -> the transaction was included in the blockchain
- delete the transaction draft / draft transaction? not sure which is good.
### settings
- rescan THE blockchain
- 0 recovery.... select one (no option available)

I didn't yet test with expired/soon to expire coins

**Comment by darosior** [comment]
Thanks for having a look. I've addressed most of this and other findings in #482. Some small comments on the specifics below that can be ignored.

> Your next timelock will expire in ...

I'm not sure it's clearer. 

> I would put this sentence in grey

Unrelated?

> Deposit: I think it makes sense, but

Took some time to get the context here... It's about the transaction details view.

> amount (ex:0.001) -> amount (in BTC)

Hmm. That's a good point we should mention amount ought to be specified in BTC. Maybe even make it clearer than just in the grey example.

> we should have the unit displayed in the box

Yeah. Not sure how but we should make units clearer indeed.

> delete the transaction draft / draft transaction? not sure which is good.

I reverted this language to use PSBTs, to be consistent with our move out of "transaction drafts".

> 0 recovery.... select one (no option available)

https://github.com/wizardsardine/liana/issues/483
