### ISSUE TITLE
GUI: synchronisation screen - more info.

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#646]
The current sync screen is this:
![image](https://github.com/wizardsardine/liana/assets/15522963/7984bf2f-8313-44af-ab7c-9f6fb2e6f798)

Now that Core can me managed by Liana, it requires more information.

Disclaimer (when sync is over 98%/about a month):
Bitcoin Core is synchronising the blockchain. This may take a few minutes, depending the last time it was done, your internet connection, and your computer performance.

Disclaimer (when sync is between 90%-98% / up to a year ago):
Bitcoin Core is synchronising the blockchain. This will take a while depending the last time it was done, your internet connection, and your computer performance.

Disclaimer (when sync is under 90%):
Bitcoin Core is synchronising the blockchain. A full synchronisation typically take a few days, and is resource intensive. Once the initial synchronisation is done, the next ones will be much faster.

We should also display the progress number, with enough digits to make is look like it's not stalled. Probably at least XX.XX%

**Comment by pythcoiner** [comment]
what about display <block_validation_height> / <headers_height> ?

**Comment by darosior** [comment]
> what about display <block_validation_height> / <headers_height> ?

It would have to be passed through from lianad and i think we shouldn't add anything Bitcoin Core specific in the JSONRPC interface.

**Comment by pythcoiner** [comment]
where we get the sync % from?

**Comment by darosior** [comment]
The daemoN.
------- Original Message -------

**Comment by pythcoiner** [comment]
waht you call the daemon?

**Comment by darosior** [comment]
The Liana software is in two parts: the daemon (`lianad`) that implements the core logic, and the GUI (`liana-gui`) that acts as a sophisticated wrapper around it.

**Comment by pythcoiner** [comment]
OK, that was what I got, just was confused bc you mentioned it as `lianad` and then as  `daemon`.

**Comment by pythcoiner** [comment]
i notice one thing today, when we get a new peer, a message about the peer overwrite the synch info, it ould be nice do display it separately or as a log.

**Comment by darosior** [comment]
To whomever gets to tackle this. I think this issue is now simply about adding some context messages (quoting OP):
> Disclaimer (when sync is over 98%/about a month):
Bitcoin Core is synchronising the blockchain. This may take a few minutes, depending the last time it was done, your internet connection, and your computer performance.
>
> Disclaimer (when sync is between 90%-98% / up to a year ago):
Bitcoin Core is synchronising the blockchain. This will take a while depending the last time it was done, your internet connection, and your computer performance.
>
> Disclaimer (when sync is under 90%):
Bitcoin Core is synchronising the blockchain. A full synchronisation typically take a few days, and is resource intensive. Once the initial synchronisation is done, the next ones will be much faster.
