### ISSUE TITLE
[GUI] Payments sometimes don't show up at start.

### ISSUE THREAD

**Issue by kloaec** [wizardsardine/liana#726]
Sometimes starting Liana, payments don't show up until Lianad refreshes.
In this screenshot (i hid the balance and expiration), there should be many payments listed, but it's empty.
![Screenshot from 2023-10-16 10-52-22](https://github.com/wizardsardine/liana/assets/15522963/d55b7a01-69eb-4f19-a955-919e33384a5d)

**Comment by darosior** [comment]
This should be fixable for now by simply making sure the daemon's poller synchronized itself with bitcoind before returning `sync == 1`.

**Comment by darosior** [comment]
So @kloaec experienced this on mainnet when the sync isn't 1.0, as bitcoind is still validating some blocks after having caught up on the headers. I believe this is due to a progress so close to 1.0 that we round it up to 1. We could fix it by checking both the verification progress and the header count vs blocks count from `getblockchaininfo`. Or maybe just checking header vs blocks is OK? This is a hot loop so i'd rather not make two calls.
