### ISSUE TITLE
Standard patterns for wallet creation

### ISSUE THREAD

**Issue by pythcoiner** [wizardsardine/liana#835]
Should we offer user a way to quick & safely create some commons patterns:
- decaying multisig with n signers
- primary key or recovery key(s) + timelock
- ...?

**Comment by darosior** [comment]
Yes. We've been talking about this since the beginning. This requires an overhaul of the policy builder screen in the installer but i think we should make it possible to use more powerful patterns (like #611) but hide this behind an "advanced" or "custom" menu and by default have a list of simple templates.

It's not clear to me how we would make the UX of this non-techie-friendly though.

**Comment by pythcoiner** [comment]
this have been implemented in #1366 & #1399
