### ISSUE TITLE
GUI: RBF: improve feerate text input

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#860]
> It might be better not to trim the feerate value as it's difficult to edit a single-digit value. It's not possible to delete the existing value and enter a new one and we have to instead add a second digit and delete the first.

_Originally posted by @jp1ac4 in https://github.com/wizardsardine/liana/pull/852#discussion_r1419802693_

**Comment by faytey** [comment]
Hello is this issue still available, i'd love to work on it and get a bit more context thanks

**Comment by darosior** [comment]
#852 introduced support for RBF'ing unconfirmed transactions in the GUI. This is presented as a button you click which opens a modal for you to set the feerate of the new transaction. The text input for the feerate of the new transaction however gets trimmed as you edit it, which makes it difficult to edit single-digit values.

@jp1ac4 what do you think a fix should be here? Simply using an untrimmed `form::Form`?

**Comment by jp1ac4** [comment]
Hi @faytey, thanks for offering to work on this issue.

I initially thought the problem was to do with trimming the form values:
https://github.com/wizardsardine/liana/blob/903328ffef8317b1f152633ac671ecd92071d8eb/gui/src/app/view/transactions.rs#L247

But we don't have this issue on the normal Send page, which uses the same type of form:
https://github.com/wizardsardine/liana/blob/903328ffef8317b1f152633ac671ecd92071d8eb/gui/src/app/view/spend/mod.rs#L172

I think rather the problem is how we handle the feerate being edited. We only save the form value if it can be parsed as `u64`:
https://github.com/wizardsardine/liana/blob/903328ffef8317b1f152633ac671ecd92071d8eb/gui/src/app/state/transactions.rs#L335

But I think we should save the form value regardless of whether it can be parsed, and only its validity should depend on the result of parsing.

**Comment by jp1ac4** [comment]
Hi @faytey, are you still working on this issue?
