### ISSUE TITLE
Hint at rescanning when user imports descriptor

### ISSUE THREAD

**Issue by darosior** [wizardsardine/liana#866]
@kloaec pointed out to me people are confused to not see their coins after importing a descriptor. I thought we told them they'll have to rescan to see them, but looks like we don't. We should.

**Comment by darosior** [comment]
I think a first step here for v5 would simply to have a message in the installer's "import" flow.

**Comment by jp1ac4** [comment]
Do you think it would be worth having this message in its own step in case later we want to let the user enter the rescan timestamp as part of the installer? For now, this step could consist of just the message and possibly a checkbox to confirm the user has understood.

I could otherwise add the message to an existing step.

**Comment by darosior** [comment]
I would rather have it as part of one of the existing steps for now.
